var annotated_dup =
[
    [ "configmaps", "d8/d68/namespaceconfigmaps.html", "d8/d68/namespaceconfigmaps" ],
    [ "data_broker_plotter", "dd/df0/namespacedata__broker__plotter.html", "dd/df0/namespacedata__broker__plotter" ],
    [ "data_broker_plotter2", "db/d0d/namespacedata__broker__plotter2.html", "db/d0d/namespacedata__broker__plotter2" ],
    [ "gui_app", "d9/da6/namespacegui__app.html", "d9/da6/namespacegui__app" ],
    [ "lib_manager", "db/d5b/namespacelib__manager.html", "db/d5b/namespacelib__manager" ],
    [ "mars", "df/d48/namespacemars.html", "df/d48/namespacemars" ],
    [ "osg_lines", "da/d50/namespaceosg__lines.html", "da/d50/namespaceosg__lines" ],
    [ "osg_material_manager", "dc/d37/namespaceosg__material__manager.html", "dc/d37/namespaceosg__material__manager" ],
    [ "osg_plot", "d6/d73/namespaceosg__plot.html", "d6/d73/namespaceosg__plot" ],
    [ "osg_points", "d7/d3f/namespaceosg__points.html", "d7/d3f/namespaceosg__points" ],
    [ "osg_terrain", "da/d98/namespaceosg__terrain.html", "da/d98/namespaceosg__terrain" ],
    [ "osg_text", "d5/d33/namespaceosg__text.html", "d5/d33/namespaceosg__text" ],
    [ "Ui", "dc/df0/namespace_ui.html", "dc/df0/namespace_ui" ],
    [ "__classname___MainWin", "d1/d20/class____classname_______main_win.html", "d1/d20/class____classname_______main_win" ],
    [ "CrossWidget", "da/dc1/class_cross_widget.html", "da/dc1/class_cross_widget" ],
    [ "item", "d6/dd8/structitem.html", "d6/dd8/structitem" ],
    [ "item_cleanup_list", "d3/db3/structitem__cleanup__list.html", "d3/db3/structitem__cleanup__list" ],
    [ "JoystickInterface", "d2/d26/class_joystick_interface.html", "d2/d26/class_joystick_interface" ],
    [ "JoystickWidget", "df/dd0/class_joystick_widget.html", "df/dd0/class_joystick_widget" ],
    [ "SkyDome", "d5/d8b/class_sky_dome.html", "d5/d8b/class_sky_dome" ],
    [ "SphereSegment", "d6/de3/class_sphere_segment.html", "d6/de3/class_sphere_segment" ],
    [ "succ_cleanup_list", "d4/df6/structsucc__cleanup__list.html", "d4/df6/structsucc__cleanup__list" ],
    [ "successor", "d5/d90/structsuccessor.html", "d5/d90/structsuccessor" ],
    [ "Ui_CrossWidgetClass", "d6/d70/class_ui___cross_widget_class.html", "d6/d70/class_ui___cross_widget_class" ],
    [ "Ui_JoystickWidgetClass", "d0/df5/class_ui___joystick_widget_class.html", "d0/df5/class_ui___joystick_widget_class" ],
    [ "VirtualJoystickPlugin", "d6/d22/class_virtual_joystick_plugin.html", "d6/d22/class_virtual_joystick_plugin" ],
    [ "VizPlugin", "d5/d61/class_viz_plugin.html", "d5/d61/class_viz_plugin" ]
];