sudo apt-get install cmake
sudo apt-get install git
sudo apt-get install git-core
sudo apt-get install libopenscenegraph-dev
sudo apt-get install libqt4-dev
sudo apt-get install zlib1g-dev
sudo apt-get install libcv-dev
sudo apt-get install libcvaux-dev
sudo apt-get install libhighgui-dev
